name: connectivity_widget
description: A widget that shows the user if the phone is connected to the internet or not
version: 0.1.0+1
author: Gonçalo Palma <solid.goncalo@gmail.com>
homepage: https://github.com/Vanethos/flutter_connectivity_widget/
issue_tracker: https://github.com/Vanethos/flutter_connectivity_widget/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.0
  connectivity: ^0.4.3+2
  stream_disposable: ^0.1.0
  dio: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
